### ISSUE TITLE
Can you make a version for MacOS

### ISSUE THREAD

**Issue by virejdasani** [Patrick-web/electron-app-store#1]
In the releases tab, there is only a version for windows, could you add one for MacOS too?

**Comment by Patrick-web** [comment]
Yea. Am currently on windows. But am planning on adding a github action to build for mac and linux. In the meantime you can help out by cloning the repo on your mac and running the build command

**Comment by Patrick-web** [comment]
I've published the .dmg and .appimage. DONE
