### ISSUE TITLE
The title bar title for the app doesn't look great

### ISSUE THREAD

**Issue by virejdasani** [Patrick-web/electron-app-store#3]
![Screenshot 2021-08-23 at 8 44 11 AM](https://user-images.githubusercontent.com/67495678/130385253-8ee707ae-9958-43cc-8dd9-b92038d578bb.png)
I think the app title should be `Electron App Store` instead of `electron-app-store`

**Comment by Patrick-web** [comment]
Oh let me fix that. What do you think of a custom title bar by the way?

**Comment by virejdasani** [comment]
Cool and I think a custom title bar would be cool :)

**Comment by Rajdeep-TG** [comment]
> Cool and I think a custom title bar would be cool :)

What do you mean by a custom title bar ?

**Comment by virejdasani** [comment]
> What do you mean by a custom title bar ?

I was replying to Patricks comment: `What do you think of a custom title bar by the way?`

https://www.npmjs.com/package/custom-electron-titlebar

**Comment by Rajdeep-TG** [comment]
> > What do you mean by a custom title bar ?
> 
> I was replying to Patricks comment: `What do you think of a custom title bar by the way?`
> 
> https://www.npmjs.com/package/custom-electron-titlebar

The existing app is so great. I think that the Custom Title Bar wouldn't make the app look cool.
If you want a custom title bar in the app, then I can create a pull request.

**Comment by virejdasani** [comment]
> > > What do you mean by a custom title bar ?
> > 
> > 
> > I was replying to Patricks comment: `What do you think of a custom title bar by the way?`
> > https://www.npmjs.com/package/custom-electron-titlebar
> 
> The existing app is so great. I think that the Custom Title Bar wouldn't make the app look cool.
> If you want a custom title bar in the app, then I can create a pull request.

I don't mind it either way :)

**Comment by Rajdeep-TG** [comment]
This Feature Request had been added to our roadmap.
